<?php
namespace App\Controllers;

class CustomPage extends BaseController {
  
  
  public function __construct() {
  
    parent::__construct(); 
    
    //The Model for this Controller
    $this->model = new \App\Models\CustomPage_Model; 
    
    $this->mustache->assign('page_title', $this->model->Get_Title());
    
  }
    
  public function CustomPage() {
    //check if page is generated by extensions
    global $page_name;
    $check_ext = $this->model->check_if_page_is_by_ext($page_name);

    if($check_ext < 1) {
      //custom page content
      $this->mustache->addHelper('legacy', [
          'php' => function() {
              global $page_name;
              ob_start();
              include 'custom_page_content/'.$page_name.'.php';
              return ob_get_clean();
          },
      ]);
    }
  }
 
 
  
};